name: vista_tv
version: 1.0.0+1
publish_to: none
description: Vista TV native app.
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

flutter:
  uses-material-design: true
